### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by KimBruce** [gracelang/grace-web-editor#27]
The web editor now very nicely translates -> to an arrow, and [[...]] to compressed versions of the brackets that look quite nice.

However, this causes problems when copying elsewhere.  When I write a program and copy it into TexShop, the arrow is fine, but when run to create pdf, it turns into a "?".  Unfortunately, the [[ is worse, it is pasted in TexShop as a "?" even before being compiled.

I like the way those characters look in the web editor, but the difficulty of transferring into LaTeX (it's even worse if it is just imported from a ".grace" file) is a significant disadvantage for those of us writing documentation.  Perhaps there could be a setting that does not do the conversion?

**Comment by kjx** [comment]
As I said elsewhere: I think there are only too good options here: 

Either: commit to Unicode, remove the ascii trigraphs, LaTeX or anything else must also take Unicode if it wants to handle Grace. 

Or: stay with ASCII, remove the ascii trigraphs, editors etc can display things however they want to but saving/cutting/pasting must all be ASCII.

**Comment by apblack** [comment]
What's a trigraph?

**Comment by kjx** [comment]
C++'s name for their ascii equivalents to operators etc.   technically we have digraphs - the ascii longhands like -> and [[ and != for the Unicode characters I can't easily type on my phone.

**Comment by apblack** [comment]
Pdf LaTeX doesn't think in Unicode, but other Latex do.  However, the grace.sty that we are using for the spec does the right conversions, and will typeset programs containing ⟦, → and ⟧ correctly. (I just updated it so that the work outside of listing environments as well as inside.)  Try this LaTeX:

```latex
\documentclass[11pt]{article}
\usepackage{graphicx}
\usepackage{grace}

\textwidth = 6.5 in
\textheight = 9 in
\oddsidemargin = 0.0 in
\evensidemargin = 0.0 in
\topmargin = 0.0 in
\headheight = 0.0 in
\headsep = 0.0 in
\parskip = 0.2in
\parindent = 0.0in

\newtheorem{theorem}{Theorem}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{definition}{Definition}

\title{Grace brackets in LaTeX}
\author{Andrew P Black}
\begin{document}
\date{15 August 2016}
\maketitle
Here is an example Grace program, containing ⟦, → and ⟧.
\begin{lstlisting}
method identity⟦T⟧(x:T) → T
	x
} 
\end{lstlisting}
And here it is again using the ``grace'' environment'
\begin{grace}
method identity⟦T⟧(x:T) → T
	x
} 
\end{grace}

 \end{document}
```
Here is the output:
[unicodeTest.pdf](https://github.com/gracelang/grace-web-editor/files/419212/unicodeTest.pdf)

I'm surprised that TeXshop doesn't render your brackets correctly, because I though that it had always allowed Unicode.  It may depend on the Preferences that you have set.  In the "source" pane of the TexShop preferences, I have "encoding" set to "Unicode (UTF-8)".  I can paste brackets and arrows to and from the web IDE and TeXShop (Version 3.66) without problem.

**Comment by KimBruce** [comment]
I’m trying to include a ‘$’ in code inside the lstlisting environment.  It used to work before I shifted to utf-8, but now it shifts me into math mode and chokes.  I’ve tried writing \$, but that makes it even worse.  Anyone know the magic to get it right?


Kim

**Comment by Dmitri-2** [comment]
I have added a unicode refactoring option in the Refactoring menu that replaces all unicode characters in a file with their ASCII equivalents (commit 5cea9f9). I am also looking at adding a Settings option to disable the automatic unicode conversion in the editor. I have not tested this commit thoroughly, so let me know if there are any issues. (I don't think there should be any, as it does a simple find and replace of the unicode characters.)

**Comment by apblack** [comment]
Kim this is completely off-topic here; your problems with LaTeX are not related to unicode, and even less to the grace-web-editor   

The listings package has the option "mathescape", which enables math mode inside a listing.  It's turned on by the Grace language definition that you loaded.  If you turn it off, then $ won't give you math mode.  (I think that it's on by default because that's what _pandoc_ expects, but I may be mis-remembering).

I'm not sure if $ will typeset, though.  Some writers on stackoverflow suggest using a literate setting in the language definition, like this:

        literate={\$}{{\textcolor{blue}{\$}}}1

where the use of blue text is just to make it clear what is going on.
