### ISSUE TITLE
Reloading a file gives bad error message

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#40]
Moved from [minigrace #217](https://github.com/gracelang/minigrace/issues/217)

If you re-load a file that has already been loaded (and perhaps compiled) on the system, you get the following warning (if the file's name is Vehicle.grace):

""Vehicle" is a built-in module. Are you sure you want to overwrite it? Doing so could cause unpredictable behavior!"

A warning is appropriate, but it is not built-in (at least in this case). Saying something like "you are replacing an existing modules, please be certain this is what you want to do" might be more helpful.

**Comment by Dmitri-2** [comment]
When you say "re-load," do you mean uploading/creating a new file of the same name? Or re-compiling a file that has already been compiled?

**Comment by Dmitri-2** [comment]
I'm having a very hard time replicating this issue. I know that it exists because on some rare occasions it does occur. However, if anyone runs across a consistent way to replicate this, it would be very helpful.

**Comment by Dmitri-2** [comment]
This should be fixed with commit c95407d. From what I can tell, this would occur when already compiled files were deleted from inside directories, or were inside of directories that were deleted. The deletion process for compiled modules (that triggers the confusing warning message), was broken by the file identifier. This has been fixed, and the deletion process has also been refactored for other cases. 

My replication process for this issue (for IDE v146 and earlier) was: 
1.  Create a file "test.grace"
2.  Move "test.grace" to a folder 
3.  Compile, then delete "test.grace"
4. Attempt to upload a file named "test.grace". This should result in the unneeded "built-in module" alert.
